platform :ios, '9.0'

use_frameworks!

target 'WeiBo' do

pod 'Alamofire', '~> 4.4'
pod 'Kingfisher', '~> 3.1.1'
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'SnapKit'
pod 'SDWebImage'
pod 'MJRefresh'
#pod 'HYLabel'



end
